#ifndef NRPYELL_BINARY_FORMAT_H
#define NRPYELL_BINARY_FORMAT_H

#define NRPYELL_BINARY_MAGIC "NRPYELL3"
#define NRPYELL_BINARY_MAGIC_LEN 8
#define NRPYELL_BINARY_VERSION 1

enum NRPYELL_solution_field_index {
  NRPYELL_SOL_UUGF = 0,
  NRPYELL_SOL_PSI_BACKGROUNDGF = 1,
  NRPYELL_SOL_ADD_TIMES_AUUGF = 2,
  NRPYELL_SOL_RESIDUAL_HGF = 3,
  NRPYELL_SOL_NUM_GFS = 4
};

#endif // NRPYELL_BINARY_FORMAT_H
